   
name: docker-image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
      imageRepoBase:
        description: 'imageRepoBase'
        required: true
      buildImage:
        description: 'buildImage'
        required: true
      packageName:
        description: 'packageName'
        required: true
env:
  version: ${{ github.event.inputs.version || 'dev' }}
  imageRepoBase: ${{ github.event.inputs.imageRepoBase || 'tjushilei' }}
  buildImage: ${{github.event.inputs.buildImage || 'components/image-builder-mk3:app'}}
  packageName: ${{github.event.inputs.packageName || 'app'}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: readyEnv
      run: |
        sudo apt-get install git
        sudo apt-get install golang-go
        wget https://nodejs.org/dist/v12.22.1/node-v12.22.1-linux-x64.tar.gz
        tar -zxvf node-v12.22.1-linux-x64.tar.gz
        cd node-v12.22.1-linux-x64
        pwd
        go version
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: build
      run: |
        mkdir leewaybin
        cd leewaybin
        wget https://github.com/gitpod-io/leeway/releases/download/v0.2.9/leeway_0.2.9_Linux_x86_64.tar.gz
        tar -zxvf leeway_0.2.9_Linux_x86_64.tar.gz
        export PATH=$PATH:/home/runner/work/gitpod/gitpod/leewaybin
        cd ..
        mkdir gokartbin
        cd gokartbin
        # clone the GoKart repo
        git clone https://github.com/praetorian-inc/gokart.git

        # navigate into the repo directory and build
        cd gokart
        go build
        # Move the gokart binary into your path
        mv ./gokart /usr/local/bin
        cd ..
        leeway build ${buildImage}
