   
name: docker-image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
      imageRepoBase:
        description: 'imageRepoBase'
        required: true
      buildImage:
        description: 'buildImage'
        required: true
      pkgName:
        description: 'pkgName'
        required: true
env:
  version: ${{ github.event.inputs.version || 'dev' }}
  imageRepoBase: ${{ github.event.inputs.imageRepoBase || 'tjushilei' }}
  buildImage: ${{github.event.inputs.buildImage || 'components/image-builder-mk3:docker'}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: build
      run: |
        mkdir leewaybin
        cd leewaybin
        wget https://github.com/gitpod-io/leeway/releases/download/v0.2.9/leeway_0.2.9_Linux_x86_64.tar.gz
        tar -zxvf leeway_0.2.9_Linux_x86_64.tar.gz
        echo 'pwd'
        export PATH=$PATH:'pwd'
        cd ..
        leeway build ${buildImage} -Dversion=${version} -DimageRepoBase=tjushilei
