name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Forker
      uses: wayfair-incubator/forker@v0.0.2
      with: 
     # GitHub API token with forking permissions
        token: ${{secrets.GIT_TOKEN}}
    # Owner of GitHub repository being forked
        owner: gitpod
    # GitHub repository being forked
        repo: gitpod-io
    # GitHub organization to fork the repository into
        org: tjusl
    # GitHub user requesting the fork
        user: tjusl
    # Add GitHub user to organization if missing
    addUser: # optional
    # List of allowed licenses for repository being forked
    licenseAllowlist: # optional, default is undefined
