name: Fetch upstream

on: 
  push:
#  schedule:
#    - cron: "0 16 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: GitHub Sync to Upstream Repository
      uses: 135e2/sync-upstream-repo@master
      with:
        upstream_repo: https://github.com/gitpod-io/gitpod.git
        upstream_branch: main
        local_branch: main
        github_token: ${{ secrets.GIT_TOKEN }}
