name: sync-upstream
on:
  push: 
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: git config
      run: |
        git config --global user.email "tjusl@126.com"
        git config --global user.name "tjusl"
    
    - name: fork-sync-all-branches
      uses: anatawa12/fork-sync-all-branches@v1.0.1
      with:
        owner: gitpod-io
        github_token: ${{secrets.ACCESS_TOKEN}}
        origin: gitpod-io/gitpod
