name: sync-upstream
on:
  push: 
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: git config
      run: |
        git config --global user.email "tjusl@126.com"
        git config --global user.name "tjusl"
    
    - name: Fork Sync
      uses: tgymnich/fork-sync@v1.2.1
      with:
        owner: gitpod-io
        github_token: ${{secrets.ACCESS_TOKEN}}
        head: main
        base: main
        merge_method: merge
        pr_title: fork sync
        pr_message: fork
        ignore_fail: failure
