name: sync-upstream
on:
  push: 
  schedule:
    - cron: "0 0 * * *"
env:
  # Default values will be used by cron job
  PARENT_COMMIT: ${{ github.event.inputs.parent_commit || 'upstream/main' }}
  UPDATE_BRANCH: ${{ github.event.inputs.update_branch || 'main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: git config
      run: |
        git config --global user.email "tjusl@126.com"
        git config --global user.name "tjusl"
    
    - name: Upstream Sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
      with:
        target_sync_branch: main
        target_repo_token: ${{ secrets.ACCESS_TOKEN }}
        upstream_repo_access_token: ${{ secrets.ACCESS_TOKEN }}
        upstream_sync_repo: gitpod-io/gitpod
        upstream_sync_branch: main
        
        
