name: sync-upstream
on:
  push: 
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: git config
      run: |
        git config --global user.email "tjusl@126.com"
        git config --global user.name "tjusl"
    
    - name: Sync-Fork-action
      uses: XueMoMo/Sync-Fork-action@v1.0.6
      with:
        owner: gitpod-io
        github_token: ${{secrets.ACCESS_TOKEN}}
        upstream_repository: gitpod-io/gitpod
        upstream_branch: main
        target_branch: main
        git_user: tjusl
        git_email: tjushilei@126.com
        
