name: sync-upstream
on:
  push: 
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: git config
      run: |
        git config --global user.email "tjusl@126.com"
        git config --global user.name "tjusl"
    - name: Fork Sync
      uses: VitorNoVictor/fork-news@v1.0.0
      with:
        access-token: ${{secrets.ACCESS_TOKEN}}
        from-repository: gitpod-io/gitpod
        to-branch: main
        from-branch: main
        pr-title:  Fork News - Updates from the parent repository
        pr-description: Here are the latest changes from the parent repository.
